###########################
name: bugless-checker

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# referenced from https://github.com/lework/kainstall/actions/runs/4550327818/workflow and https://docs.github.com/en/actions/examples/using-scripts-to-test-your-code-on-a-runner
#

#############################
# Start the job on all push #
#############################
on:
  push:
  pull_request:
    branches: [master]
    paths-ignore:
      - '**.README.md'
      - '**./.git/**'
      - '**LICENSE'
      - '**.blank.yml'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: bugless-checker
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Setup script executable
        run: |
          chmod +x *.sh
      ################################
      # Run Linter against code base #
      ################################
      - name: bugless-checker
        uses: github/super-linter@v3.17.0
        env:
          VALIDATE_ALL_CODEBASE: false
          ERROR_ON_MISSING_EXEC_BIT: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
